### ISSUE TITLE
Question about LoRA support

### ISSUE THREAD

**Issue by felipemello1** [zyushun/Adam-mini#18]
Hi, thanks for the public implementation! What should I do if I am finetuning only Query and Value using LoRA?

Do i need to change anything? It seems that the code only accounts for Key and Query (not Value), and lora layers wont be added to optim_groups.

**Comment by chcoliang** [comment]
Hi @felipemello1 ! I don't think you need to change anything to support LoRA, since all trainable parameters will be added in optim_groups (Key and Query are special since we have to use different strategies for these two blocks).

If you have any other questions, feel free to ask for help.
