### ISSUE TITLE
pretrain llama can only use linear decay

### ISSUE THREAD

**Issue by Wongboo** [zyushun/Adam-mini#21]
[train.py](https://github.com/zyushun/Adam-mini/blob/main/examples/llama3_8b/train.py) use [lr_scheduler](https://github.com/zyushun/Adam-mini/blob/main/examples/llama3_8b/torchtitan/lr_scheduling.py) for lr scheduling, which only supports linear decay. but [paper](https://github.com/zyushun/Adam-mini/blob/main/examples/llama3_8b/torchtitan/lr_scheduling.py) says llama pretraining use cosine decay. Which one is right?

**Comment by Wongboo** [comment]
I only refer to llama pretraining, not gpt pretraining and llama finetuning.

**Comment by zyushun** [comment]
Hi @Wongboo, thanks for the question!
Both schedules are fine. As the Torchtitan uses linear decay as the default choice, you can try linear decay first.

**Comment by Wongboo** [comment]
It is weird that llama pretraining code based on Torchtitan in your repo cannot use cosine decay. But the paper states that you gays use cosine decay in llama pretraining.

**Comment by Wongboo** [comment]
Which intrigues my interest: what is the true baseline setting in your llama pretraining?

**Comment by zyushun** [comment]
Hi @Wongboo ,

In the paper we used TinyLlama codebase. But later we found certain unexpected error when saving ckpts, so we shift to torchtitan recently.


"what is the true baseline setting in your llama pretraining?" When using Torchtitan, our baseline is adamw with 3e-4 + linear decay

**Comment by Wongboo** [comment]
OK
